controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_base_rockbreaker
      - joint_brazoa
      - joint_brazob
      - joint_hammer
  - name: joint_group_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_base_rockbreaker
      - joint_brazoa
      - joint_brazob
      - joint_hammer